### ISSUE TITLE
A method for turning off the automatic clearlag?

### ISSUE THREAD

**Issue by cshcrafter** [Elrol/Server-Utilities#19]
Hi there,

I run a small modded server and was wondering if there's any way to turn off the automatic clearlag that runs. Is that possible in config somewhere? I wasn't really able to find any information mentioned anywhere. Thanks for your time :)

-CSH

**Comment by KunoiSayami** [comment]
Maybe can edit configure file to disable it
<details>
  <summary> config/serverutils/server-utils.toml </summary>

```toml
	[Commands.clearlag]
		item = true
		#Range: > 0
		delay = 0
		aliases = ["clearlag"]
		perm = "serverutils.clearlag"
		enable = false
		hostile = true
		#Range: > 0
		cooldown = 0
		passive = false
		#Range: > 0
		frequency = 5
```

</details>

But I tried set `enable` to `false`, it doesn't work for me.
